// svelte-simple-routing/src/routes/blog/+page.svelte
<script>
	import { onMount } from 'svelte';

	let projects = [];

	onMount(async () => {
		const response = await fetch('https://jsonplaceholder.typicode.com/posts');
		projects = await response.json();
	});
</script>

<div class="text-column">
	<h1>Blog</h1>

	<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
		{#each projects as project}
			<div class="mb-4">
				<div class="bg-white shadow-md rounded-lg p-4 hover:shadow-lg transition-shadow">
					<h2 class="text-2xl font-bold mt-2 mb-2">{project.title}</h2>º
					<p class="text-gray-600">{project.body}</p>
				</div>
			</div>
		{/each}
	</div>
</div>

// react-vite-routing/src/pages/Blog.tsx
import { useEffect, useState } from 'react'

function Blog() {
  interface Post {
    userId: number,
    id: number,
    title: string
    completed: boolean
  }

  const [posts, setPosts] = useState([] as Post[])

  useEffect(() => {
    fetch('https://jsonplaceholder.typicode.com/posts')
      .then(response => response.json())
      .then(data => setPosts(data))
  }, [])

  return (
    <div className="flex flex-col items-center justify-center m-2">
      <h1 className="col-span-3 text-3xl font-bold">Blog</h1>

      <div className="grid grid-cols-3 gap-4">
        {posts.map(post => (
          <div key={post.id} className="bg-white p-4 shadow-md rounded-md">
            <h2 className="text-xl font-bold">{post.title}</h2>
            {post.completed ? <p>Completed</p> : <p>Not completed</p>}
          </div>
        ))}
      </div>
    </div>
  )
}

export default Blog
